In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd_kota = o3d.io.read_point_cloud("../kota_circuit2.ply")
print(pcd_kota)

PointCloud with 14640197 points.


In [3]:
o3d.visualization.draw_geometries_with_editing([pcd_kota])

### Vertex normal estimation

In [76]:
kota_cropped = o3d.io.read_point_cloud("../cropped_1.ply")
o3d.visualization.draw_geometries([kota_cropped])

In [77]:
# from vertex normal estimation
kota_cropped.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.5, max_nn=50))

o3d.visualization.draw_geometries([kota_cropped])

In [78]:
# write_ascii
o3d.io.write_point_cloud("kota_cropped_ascii.ply", kota_cropped, write_ascii=True)

True

### z>=.9, -0.2<x<+0.2, -0.2<y<+0.2

In [79]:
kota_cropped_ascii = o3d.io.read_point_cloud("kota_cropped_ascii.ply")
print(kota_cropped_ascii)

PointCloud with 57495 points.


In [80]:
print("POINTS")
print(np.asarray(kota_cropped_ascii.points))
print("\nNORMALS")
print(np.asarray(kota_cropped_ascii.normals))
print("\nCOLORS")
print(np.asarray(kota_cropped_ascii.colors))

POINTS
[[-51.769  126.032  -92.8029]
 [-44.7568 116.31   -92.7263]
 [-47.5728 111.213  -92.6068]
 ...
 [-69.256  126.105  -92.3161]
 [-50.5813 106.171  -92.5063]
 [-45.9916 108.008  -92.5413]]

NORMALS
[[ 0.0119254   0.00281208  0.999925  ]
 [-0.0330682   0.0202214   0.999249  ]
 [ 0.132414    0.179811    0.974748  ]
 ...
 [ 0.208528   -0.395644   -0.894417  ]
 [-0.0253697   0.123503    0.99202   ]
 [-0.0285625   0.0934797   0.995211  ]]

COLORS
[[0.8        0.83137255 0.83529412]
 [0.40392157 0.56470588 0.31372549]
 [0.76078431 0.78431373 0.79215686]
 ...
 [0.44313725 0.48235294 0.35686275]
 [0.80784314 0.83137255 0.83137255]
 [0.74509804 0.77647059 0.78823529]]


In [81]:
points_np = np.asarray(kota_cropped_ascii.points)
normals_np = np.asarray(kota_cropped_ascii.normals)
colors_np = np.asarray(kota_cropped_ascii.colors)

filtered_points = []
filtered_normals = []
filtered_colors = []

for point, normal, color in zip(points_np, normals_np, colors_np):
    x, y, z = normal
    
    if (-0.2 < x < 0.2 and -0.2 < y < 0.2 and z >= 0.9):
        filtered_points.append(point)
        filtered_normals.append(normal)
        filtered_colors.append(color)
        
filtered_points = np.asarray(filtered_points)
filtered_normals = np.asarray(filtered_normals)
filtered_colors = np.asarray(filtered_colors)

kota_cropped_ascii.points = o3d.utility.Vector3dVector(filtered_points)
kota_cropped_ascii.normals = o3d.utility.Vector3dVector(filtered_normals)
kota_cropped_ascii.colors = o3d.utility.Vector3dVector(filtered_colors)

print(kota_cropped_ascii)

print("POINTS")
print(filtered_points)
print("\nNORMALS")
print(filtered_normals)
print("\nCOLORS")
print(filtered_colors)

PointCloud with 43689 points.
POINTS
[[-51.769  126.032  -92.8029]
 [-44.7568 116.31   -92.7263]
 [-47.5728 111.213  -92.6068]
 ...
 [-55.073  129.62   -92.7165]
 [-50.5813 106.171  -92.5063]
 [-45.9916 108.008  -92.5413]]

NORMALS
[[ 0.0119254   0.00281208  0.999925  ]
 [-0.0330682   0.0202214   0.999249  ]
 [ 0.132414    0.179811    0.974748  ]
 ...
 [ 0.0792517  -0.0187848   0.996678  ]
 [-0.0253697   0.123503    0.99202   ]
 [-0.0285625   0.0934797   0.995211  ]]

COLORS
[[0.8        0.83137255 0.83529412]
 [0.40392157 0.56470588 0.31372549]
 [0.76078431 0.78431373 0.79215686]
 ...
 [0.79215686 0.81176471 0.82352941]
 [0.80784314 0.83137255 0.83137255]
 [0.74509804 0.77647059 0.78823529]]


In [82]:
# write_ascii
o3d.io.write_point_cloud("kota_cropped_ascii_edited.ply", kota_cropped_ascii, write_ascii=True)

True

In [83]:
kota_cropped_ascii_edited = o3d.io.read_point_cloud("kota_cropped_ascii_edited.ply")
print(kota_cropped_ascii_edited)

PointCloud with 43689 points.


In [84]:
o3d.visualization.draw_geometries([kota_cropped_ascii])